services:
  # Server service
  server:
    build:
      context: ./chatapp-server
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - mern_network
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      PORT: 8000
      FRONTEND_BASE_URL: http://localhost:5173
      DB_URL: mongodb+srv://shaqeebsk1234:3hHFxs8LAq9Drnas@cluster0.au4cd8l.mongodb.net/Chatter
    depends_on:
      - mongodb
 
  # Client service
  client:
    build:
      context: ./chatapp-frontend
      dockerfile: Dockerfile
    container_name: frontend
  
    ports:
      - "5173:80"
    networks:
      - mern_network
    depends_on:
      - server

  # Database service
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    networks:
      - mern_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27017"
    volumes:
     - mydata:/data/db

  # Nginx service
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - mern_network


  
networks:
   mern_network:
    driver: bridge

# Define volumes
volumes: 
  mydata:
